### ISSUE TITLE
end recording

### ISSUE THREAD

**Issue by ahmetozalp** [t-mullen/wrtc-to-ffmpeg#6]
Hello there,

  I can't stop what I do video recording, what's the problem?

**Comment by t-mullen** [comment]
Sorry, what do you mean? You can't stop recording video?

**Comment by ahmetozalp** [comment]
yes video recording does not stop.

<img width="830" alt="Ekran Resmi 2020-06-29 21 30 38" src="https://user-images.githubusercontent.com/7665820/86042421-cf38a480-ba4f-11ea-96f1-eb57313a36df.png">

If I turn off the node, it takes off the video. (ctrl+c)

**Comment by ahmetozalp** [comment]
extra problem:

in addition, why is there only a problem with the video in the chrome browser?

https://www.youtube.com/watch?v=llTKfFNYr3c

**Comment by t-mullen** [comment]
See "Controlling the FFmpeg process" here https://github.com/fluent-ffmpeg/node-fluent-ffmpeg for how to stop the transcode. I don't know if it will work.

That problem is already known.

This library is a work-in-progress and isn't currently ready to use.

**Comment by ahmetozalp** [comment]
In addition, there is only such a problem in chrome, how can I fix it?

https://www.youtube.com/watch?v=llTKfFNYr3c

**Comment by t-mullen** [comment]
That's issue #1. It happens due to Chrome changing the input resolution after recording starts.

**Comment by ahmetozalp** [comment]
there seems to be no solution but I can't see (bad english sry)

**Comment by t-mullen** [comment]
You're right, there isn't. This module is a work-in-progress.

This means it does not work yet.

**Comment by ahmetozalp** [comment]
I think it has to be a solution tthank you.

**Comment by ahmetozalp** [comment]
the sample codes don't cause the problem in the video for some reason (chrome problem)
